// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} uUID
 * @returns {Promise.<void>}
 */
export async function RedirectPage(uUID) {
	// BEGIN USER CODE

	var form = document.createElement('form');
    document.body.appendChild(form);
    form.method = 'post';
    form.action = '/signin/';
	var input = document.createElement('input');
		input.type = 'hidden';
		input.name = 'uuid';
        input.value = uUID;
        form.appendChild(input);
    
    form.submit();

	return;
	// END USER CODE
}
