// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} user_Input
 * @returns {Promise.<void>}
 */
export async function FileSystem(user_Input) {
	// BEGIN USER CODE

	const fs = window.fs
	const path = window.path
	const getAppDataPath = window.getAppDataPath
	const myEnv = window.myEnv
	const fsPromises = fs.promises;

	const enviroment =JSON.parse(myEnv) // Move this to Deep Json? parse it out in electron?

	const appDatatDirPath = getAppDataPath(enviroment)


	console.log("Where I am Saved 🔥",appDatatDirPath)
	console.log("What you User Said",user_Input)

  try {
	const appDataFilePath = path.join(appDatatDirPath, 'hello.txt');
// Write File To Disk
	await fsPromises.writeFile(appDataFilePath,user_Input, (err) => {
		if (err) throw err;
		console.log("We put that in a TXT file");
	})
// Read File
    const rawData = await fsPromises.readFile(appDataFilePath,"utf8");
	console.log("Data from file:", rawData)
  } catch (err) {
    console.error('Error occured while reading directory!', err);
  }
	// END USER CODE
}
